### ISSUE TITLE
Add curation interface

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/cellfinder#346]
### IO
- [x]  Load XML file (implemented within [brainglobe-napari-io](https://github.com/brainglobe/brainglobe-napari-io))
- [x] Save XML file (implemented within [brainglobe-napari-io](https://github.com/brainglobe/brainglobe-napari-io))
- [x] Specifically save training data 

### Curation
- [ ] ~~Confirm a points class~~ (Not sure what this even means!)
- [x] Mark a point as a specific class (cell/non-cell)
- [ ] ~~Select points across cell & non-cell layer~~ Opened https://github.com/brainglobe/cellfinder/issues/362 to track
- [x] Mark all selected points as a specific class
- [x]  Create a new set of cell layers (inc `Layer.metadata["point_type"` attribute)

### Analysis

- [ ]  ~~Run cellfinder (assignment to brain region) class based on brainreg segmentation~~ Opened https://github.com/brainglobe/brainglobe-utils/issues/26 to track
- [x]  Extract cubes & create training YAML file 
- [ ] ~~Make training YAML portable (relative cell paths - does this work with the training plugin?)~~ Decided not to do this as absolute paths are necessary for combining >1 training dataset

### Misc

- [ ] ~~Warn when overwriting~~ Opened #363 to track
- [ ] ~~Keyboard shortcuts~~ Opened #364 to track

**Comment by adamltyson** [comment]
Closing this issue as I've converted each task to a separate issue
